// Autogenerated pantry-item notes.
//
// Takes a loose `NoteInput` (a scanned OFF product OR a stored PantryItem)
// and returns a human-readable paragraph. The **first** sentence always
// anchors on what the item *is*: product title (brand + name) plus either the
// Open Food Facts description or an inferred type from the name/category.
// Further sentences cover labels, allergens, nutrition, and storage when
// data exists.
//
// Sparse inputs (name + category only) still get an identity-first line via
// `buildIdentityFallback` — e.g."Keebler Club Crackers — snack crackers."
// instead of a generic"Snack item." stub.

export interface NoteInput {
 name: string;
 brand?: string;
 category: string;
 barcode?: string;
 unit?: string;
 description?: string;
 quantity_text?: string;
 labels_text?: string;
 allergens?: string[];
 traces?: string[];
 nutri_score?: string;
 dietary?: string[];
 nutrition_data?: Record<string, unknown>;
}

// ---- Tag normalisation ---------------------------------------------------

const TAG_SYNONYMS: Record<string, string> = {
 'bio': 'organic',
 'agriculture biologique': 'organic',
 'eu organic': 'organic',
 'ue bio': 'organic',
 'organic farming': 'organic',
 'bio europeen': 'organic',
 'vegan label': 'vegan',
 'gluten free': 'gluten-free',
 'lactose free': 'lactose-free',
 'palm oil free': 'palm-oil-free',
 'no palm oil': 'palm-oil-free',
 'fairtrade': 'fair trade',
 'fair trade certified': 'fair trade',
 'no added sugar': 'no added sugar',
 'sugar free': 'sugar-free',
 'low sugar': 'low sugar',
 'low fat': 'low fat',
 'low salt': 'low salt',
 'high protein': 'high protein',
 'high fiber': 'high fibre',
 'high fibre': 'high fibre',
 'whole grain': 'whole grain',
 'wholegrain': 'whole grain',
};

const TAG_NOISE_EXACT = new Set([
 'nutriscore', 'ecoscore', 'green dot', 'triman', 'point vert',
 'eu', 'ce', 'fsc', 'recyclable packaging', 'recyclable',
 'glass', 'plastic', 'cardboard', 'metal', 'tetrapak',
]);

function normalizeTag(raw: string): string | null {
 const cleaned = raw
 .replace(/^[a-z]{2}:/i, '')
 .replace(/[-_]/g, ' ')
 .replace(/\s+/g, ' ')
 .trim()
 .toLowerCase();
 if (!cleaned) return null;
 if (TAG_NOISE_EXACT.has(cleaned)) return null;
 if (/^(made|sold|packaged|assembled|produced) in\b/.test(cleaned)) return null;
 if (/^contains\b/.test(cleaned)) return null;
 if (cleaned in TAG_SYNONYMS) return TAG_SYNONYMS[cleaned];
 return cleaned;
}

function titleCase(s: string): string {
 return s.replace(/\b[a-z]/g, c => c.toUpperCase());
}

function joinWithCommas(items: string[]): string {
 const clean = items.map(s => s.trim()).filter(Boolean);
 if (clean.length === 0) return '';
 if (clean.length === 1) return clean[0];
 if (clean.length === 2) return `${clean[0]} and ${clean[1]}`;
 return `${clean.slice(0, -1).join(', ')}, and ${clean[clean.length - 1]}`;
}

// ---- Quantity / units ---------------------------------------------------

function formatQuantity(q: string): string {
 if (!q) return '';
 return q
 .replace(/\s+/g, ' ')
 .replace(/(\d)\s*(?:ml|millilitres?|milliliters?)\b/gi, '$1mL')
 .replace(/(\d)\s*(?:l|litres?|liters?)\b/gi, '$1L')
 .replace(/(\d)\s*(?:kg|kilograms?)\b/gi, '$1kg')
 .replace(/(\d)\s*(?:g|grams?|grammes?)\b/gi, '$1g')
 .replace(/(\d)\s*oz\b/gi, '$1oz')
 .replace(/(\d)\s*lb\b/gi, '$1lb')
 .trim();
}

function formatGrams(n: number): string {
 if (!isFinite(n) || n < 0) return '';
 if (n >= 10) return `${Math.round(n)}g`;
 if (n >= 1) return `${n.toFixed(1).replace(/\.0$/, '')}g`;
 return `${n.toFixed(2)}g`;
}

// ---- Leads ---------------------------------------------------------------

/**"Brand Name" + product line, or name alone if the name already starts with the brand. */
function formatProductDisplayName(p: Pick<NoteInput, 'name' | 'brand'>): string {
 const name = (p.name || '').trim();
 const brand = (p.brand || '').trim();
 if (!name && !brand) return '';
 if (!brand) return name;
 if (!name) return brand;
 if (name.toLowerCase().startsWith(brand.toLowerCase())) return name;
 return `${brand} ${name}`;
}

/** Join a product title with a short"what it is" clause (identity-first notes). */
function anchorLead(title: string, what: string): string {
 const w = what.trim().replace(/\.+$/, '');
 if (!title) return `${w}.`;
 if (w.toLowerCase().startsWith(title.toLowerCase())) return `${w}.`;
 return `${title} — ${w.charAt(0).toLowerCase()}${w.slice(1)}.`;
}

// OFF occasionally sets `generic_name_en` to useless stubs like
//"a personal-care item" or"food". Treat those as empty so we can fall
// back to our category-aware lead generator.
function isGenericDescription(desc: string): boolean {
 const trimmed = desc.trim().toLowerCase().replace(/[.!?]+$/, '');
 if (trimmed.length < 4) return true;
 if (/^a?n?\s*(personal[\s-]care|household|food|grocery|cosmetic|beverage|snack|dairy|bakery)\s*(item|product)?$/.test(trimmed)) return true;
 if (['food', 'item', 'product', 'beverage', 'snack'].includes(trimmed)) return true;
 return false;
}

function formatLead(product: NoteInput): string | null {
 const raw = (product.description || '').trim();
 if (!raw || isGenericDescription(raw)) return null;
 const qty = formatQuantity(product.quantity_text || '');
 const clean = raw[0].toUpperCase() + raw.slice(1).replace(/[.!?]+$/, '');
 const body = qty ? `${clean} — ${qty}` : clean;
 const title = formatProductDisplayName(product);
 if (!title) return `${body}.`;
 const bodyLower = body.toLowerCase();
 const tLower = title.toLowerCase();
 if (bodyLower.startsWith(tLower) || bodyLower.includes(tLower)) return `${body}.`;
 return anchorLead(title, body);
}

// ----"What is this?" — inferred from the product name, then category ----

function nameBasedWhatItIs(p: NoteInput): string | null {
 const n = p.name.toLowerCase();
 if (/\bcracker(s)?\b/.test(n)) return 'Snack crackers';
 if (/\b(chip|chips|crisp|crisps)\b/.test(n)) return 'Chips or crisps';
 if (/\b(pretzel|pretzels)\b/.test(n)) return 'Pretzels';
 if (/\b(popcorn)\b/.test(n)) return 'Popcorn';
 if (/\b(cereal)\b/.test(n)) return 'Breakfast cereal';
 if (/\b(granola|muesli)\b/.test(n)) return 'Granola or muesli';
 if (/\b(oatmeal|porridge)\b/.test(n)) return 'Hot cereal';
 if (/\bmilk\b/.test(n)) {
 if (/\b(almond|oat|soy|coconut|cashew|rice|pea)\b/.test(n)) return 'Plant-based milk';
 return 'Cow\'s milk';
 }
 if (/\b(cream)\b/.test(n) && !/\bice\b/.test(n)) return 'Cream';
 if (/\b(butter)\b/.test(n)) return 'Butter or spread';
 if (/\b(yoghurt|yogurt)\b/.test(n)) return 'Yoghurt';
 if (/\b(cheese)\b/.test(n)) return 'Cheese';
 if (/\b(egg)s?\b/.test(n)) return 'Eggs';
 if (/\b(pasta|spaghetti|penne|fusilli|macaroni|linguine|ravioli)\b/.test(n)) return 'Pasta';
 if (/\b(rice)\b/.test(n) && !/\b(crisp|cake|wine|vinegar)\b/.test(n)) return 'Rice';
 if (/\b(quinoa|couscous|bulgur)\b/.test(n)) return 'Grains or pseudograins';
 if (/\b(flour)\b/.test(n)) return 'Flour';
 if (/\b(bread|bagel|bun|roll|croissant|muffin)\b/.test(n)) return 'Bread or bakery';
 if (/\b(wine)\b/.test(n)) return 'Wine';
 if (/\b(beer|lager|ale|ipa|stout|porter)\b/.test(n)) return 'Beer';
 if (/\b(whisky|whiskey|bourbon|scotch|vodka|gin|rum|tequila|brandy|cognac|liqueur)\b/.test(n)) return 'Spirits';
 if (/\b(sparkling water|seltzer|soda water|tonic)\b/.test(n)) return 'Sparkling or tonic water';
 if (/\bjuice\b/.test(n)) return 'Juice';
 if (/\bcoffee\b/.test(n)) return 'Coffee';
 if (/\btea\b/.test(n)) return 'Tea';
 if (/\b(cola|soda|soft drink|pop)\b/.test(n)) return 'Soft drink';
 if (/\b(sauce|ketchup|mayo|mustard|dressing|marinade)\b/.test(n)) return 'Sauce or condiment';
 if (/\b(soup)\b/.test(n)) return 'Soup';
 if (/\b(honey|jam|marmalade|spread)\b/.test(n)) return 'Spread or sweetener';
 if (/\b(ice cream|gelato|sorbet)\b/.test(n)) return 'Frozen dessert';
 if (/\b(frozen)\b/.test(n) || p.category === 'Frozen') return 'Frozen food';
 if (/\b(canned|tin)\b/.test(n)) return 'Canned good';
 if (/\b(spice|seasoning|herb)\b/.test(n)) return 'Spice or seasoning';
 if (/\b(candy|chocolate|sweet)\b/.test(n)) return 'Candy or confectionery';
 if (/\b(nut|almonds|walnuts|peanuts|cashews)\b/.test(n)) return 'Nuts or seeds';
 if (/\b(meat|beef|pork|chicken|turkey|lamb|bacon|sausage)\b/.test(n)) return 'Meat or poultry';
 if (/\b(fish|salmon|tuna|shrimp|seafood)\b/.test(n)) return 'Fish or seafood';
 return null;
}

function categoryWhatItIs(category: string): string {
 const m: Record<string, string> = {
 'Bread & Bakery': 'Baked goods',
 'Breakfast & Cereal': 'Breakfast food',
 'Canned & Jarred': 'Shelf-stable canned or jarred food',
 'Condiments & Sauces': 'Condiment or sauce',
 'Dairy & Eggs': 'Dairy or eggs',
 'Frozen': 'Frozen food',
 'Grains & Pasta': 'Grains, pasta, or similar staples',
 'Meat & Seafood': 'Meat or seafood',
 'Nuts & Snacks': 'Snacks',
 'Spices & Seasonings': 'Spices or seasonings',
 'Sweets & Candy': 'Candy or sweets',
 'Winery & Spirits': 'Alcoholic beverage',
 'Beverages': 'Beverage',
 'Household': 'Household product',
 'Personal Care': 'Personal-care product',
 'Fruits': 'Fresh fruit',
 'Vegetables': 'Fresh vegetables',
 'Other': 'Pantry item',
 };
 return m[category] ?? 'Pantry item';
}

function buildIdentityFallback(p: NoteInput): string | null {
 const title = formatProductDisplayName(p);
 const fromName = nameBasedWhatItIs(p);
 const fromCat = categoryWhatItIs(p.category);
 const what = fromName ?? fromCat;
 if (!title) return `${what}.`;
 return anchorLead(title, what);
}

// Dosage / product-form detection for Personal Care items.
const DOSAGE_FORMS: { re: RegExp; label: string; route?: string }[] = [
 { re: /\b(lozenge|cough drop|throat drop|pastille)s?\b/, label: 'lozenges', route: 'Dissolve slowly in the mouth as directed.' },
 { re: /\bchewable(?:\s+(?:tablet|soft)s?)?\b/, label: 'chewable tablets', route: 'Chew thoroughly before swallowing.' },
 { re: /\b(caplet|tablet)s?\b/, label: 'tablets', route: 'Take with water as directed.' },
 { re: /\b(capsule|softgel|gelcap)s?\b/, label: 'capsules', route: 'Swallow with water as directed.' },
 { re: /\b(syrup|elixir|oral liquid|oral solution)\b/, label: 'oral liquid', route: 'Use the supplied measuring device.' },
 { re: /\b(nasal )?spray\b/, label: 'spray' },
 { re: /\b(ointment|balm|salve)\b/, label: 'topical ointment', route: 'For external use only.' },
 { re: /\b(cream|lotion|moisturi[sz]er)\b/, label: 'cream', route: 'For external use only.' },
 { re: /\b(gel)\b/, label: 'gel' },
 { re: /\bpatch(?:es)?\b/, label: 'patches' },
 { re: /\bpowder\b/, label: 'powder' },
 { re: /\b(bar\s*soap|soap\s*bar)\b/, label: 'bar soap' },
 { re: /\b(body wash|shower gel)\b/, label: 'body wash' },
 { re: /\bshampoo\b/, label: 'shampoo' },
 { re: /\bconditioner\b/, label: 'conditioner' },
 { re: /\btoothpaste\b/, label: 'toothpaste' },
 { re: /\b(deodorant|antiperspirant)\b/, label: 'deodorant' },
 { re: /\bsunscreen\b/, label: 'sunscreen', route: 'Apply generously before sun exposure; reapply every 2 hours.' },
 { re: /\b(mouthwash|rinse)\b/, label: 'mouthwash' },
 { re: /\b(bandage|plaster|dressing)s?\b/, label: 'dressings' },
];

// What the product is *for* — short purpose clauses appended to the form.
function inferPurpose(name: string): string | null {
 const n = name.toLowerCase();
 if (/\b(nausea|motion sickness|anti[\s-]?nausea|vomit)/.test(n)) return 'for nausea and motion sickness relief';
 if (/\b(ginger)\b/.test(n) && /lozenge|tablet|chewable/.test(n)) return 'for nausea relief';
 if (/\b(cough|cold|flu|sore throat|congestion)\b/.test(n)) return 'for cough and cold symptom relief';
 if (/\b(allergy|antihistamine|hayfever)\b/.test(n)) return 'for allergy symptom relief';
 if (/\b(pain|headache|migraine|ibuprofen|acetaminophen|paracetamol|aspirin)\b/.test(n)) return 'for pain and headache relief';
 if (/\b(antacid|heartburn|indigestion|reflux)\b/.test(n)) return 'for heartburn and indigestion relief';
 if (/\b(sleep|insomnia|melatonin)\b/.test(n)) return 'as a sleep aid';
 if (/\b(vitamin|multivitamin|supplement|probiotic|omega|fish oil)\b/.test(n)) return 'as a dietary supplement';
 if (/\b(diarrhea|diarrhoea|laxative|constipation)\b/.test(n)) return 'for digestive relief';
 return null;
}

function buildPersonalCareLead(p: NoteInput): string | null {
 const name = p.name.toLowerCase();
 const match = DOSAGE_FORMS.find(f => f.re.test(name));
 const purpose = inferPurpose(name);
 if (match) {
 const label = match.label[0].toUpperCase() + match.label.slice(1);
 return purpose ? `${label} ${purpose}.` : `${label}.`;
 }
 if (purpose) return `Personal-care product ${purpose}.`;
 return null;
}

function buildHouseholdLead(p: NoteInput): string | null {
 const n = p.name.toLowerCase();
 if (/\blaundry detergent\b|\b(he\s+)?(liquid|powder)\s+detergent\b/.test(n)) return 'Laundry detergent.';
 if (/\bdetergent\b/.test(n)) return 'Cleaning detergent.';
 if (/\b(dish ?soap|dishwashing)\b/.test(n)) return 'Dish soap.';
 if (/\b(disinfect|sanitiser|sanitizer|bleach)\b/.test(n)) return 'Disinfectant for household surfaces.';
 if (/\bwipe(s)?\b/.test(n)) return 'Cleaning wipes.';
 if (/\b(cleaner|degreaser)\b/.test(n)) return 'Surface cleaner.';
 if (/\b(paper towel|tissue|kitchen roll)\b/.test(n)) return 'Paper product for household use.';
 if (/\b(trash bag|garbage bag|bin liner)\b/.test(n)) return 'Waste bags.';
 return null;
}

function buildDrinkLead(p: NoteInput): string | null {
 const n = p.name.toLowerCase();
 if (/\bwine\b/.test(n)) return 'Wine.';
 if (/\bbeer\b|\bale\b|\blager\b|\bstout\b|\bipa\b/.test(n)) return 'Beer.';
 if (/\b(whisky|whiskey|bourbon|scotch)\b/.test(n)) return 'Whisky.';
 if (/\b(vodka|gin|rum|tequila|brandy|cognac|liqueur)\b/.test(n)) return 'Spirits.';
 if (/\b(sparkling water|seltzer|soda water)\b/.test(n)) return 'Sparkling water.';
 if (/\bjuice\b/.test(n)) return 'Fruit juice.';
 if (/\bcoffee\b/.test(n)) return 'Coffee.';
 if (/\btea\b/.test(n)) return 'Tea.';
 if (/\b(cola|soda|soft drink|pop)\b/.test(n)) return 'Soft drink.';
 return null;
}

function buildFallbackLead(p: NoteInput): string | null {
 const title = formatProductDisplayName(p);

 switch (p.category) {
 case 'Personal Care': {
 const inner = buildPersonalCareLead(p);
 if (inner) return title ? anchorLead(title, inner.replace(/\.$/, '')) : inner;
 return buildIdentityFallback(p);
 }
 case 'Household': {
 const inner = buildHouseholdLead(p);
 if (inner) return title ? anchorLead(title, inner.replace(/\.$/, '')) : inner;
 return buildIdentityFallback(p);
 }
 case 'Fruits':
 if (title) return `${title} — fresh fruit. Rinse before eating.`;
 return 'Fresh fruit. Rinse before eating.';
 case 'Vegetables':
 if (title) return `${title} — fresh vegetables. Rinse before preparing.`;
 return 'Fresh produce. Rinse before preparing.';
 case 'Beverages':
 case 'Winery & Spirits': {
 const inner = buildDrinkLead(p);
 if (inner) return title ? anchorLead(title, inner.replace(/\.$/, '')) : inner;
 return buildIdentityFallback(p);
 }
 default: {
 const inner = buildDrinkLead(p);
 if (inner) return title ? anchorLead(title, inner.replace(/\.$/, '')) : inner;
 return buildIdentityFallback(p);
 }
 }
}

// ---- Nutrition ----------------------------------------------------------

function formatNutritionLine(product: NoteInput): string | null {
 const n = (product.nutrition_data || {}) as Record<string, number>;
 const parts: string[] = [];

 if (product.nutri_score) parts.push(`Nutri-Score ${product.nutri_score.toUpperCase()}`);

 const kcal = n['energy-kcal_100g'] ?? n['energy_100g'];
 if (kcal !== undefined && Number(kcal) > 0) parts.push(`${Math.round(Number(kcal))} kcal`);

 const sugar = n['sugars_100g'];
 if (sugar !== undefined && Number(sugar) >= 0.1) parts.push(`${formatGrams(Number(sugar))} sugar`);

 const salt = n['salt_100g'];
 if (salt !== undefined && Number(salt) >= 0.01) parts.push(`${formatGrams(Number(salt))} salt`);

 if (parts.length === 0) return null;
 if (parts.length === 1 && product.nutri_score) return `${parts[0]}.`;

 const per = product.unit === 'mL' || product.unit === 'L' ? '100 mL' : '100 g';
 return `${parts.join(' · ')} per ${per}.`;
}

// ---- Storage & safety ---------------------------------------------------

function storageHint(product: NoteInput): string | null {
 const haystack = `${product.name} ${product.description || ''}`.toLowerCase();
 const cat = product.category;

 if (cat === 'Frozen' || /\bfrozen\b|\bice cream\b/.test(haystack)) return 'Keep frozen.';
 if (cat === 'Dairy & Eggs') return 'Keep refrigerated.';
 if (cat === 'Meat & Seafood') return 'Keep refrigerated; cook thoroughly before eating.';
 if (/\bfresh\b|\bchilled\b/.test(haystack)) return 'Keep refrigerated.';

 if (cat === 'Condiments & Sauces' || cat === 'Canned & Jarred') return 'Refrigerate after opening.';
 if (cat === 'Bread & Bakery') return 'Store in a cool, dry place.';
 if (cat === 'Grains & Pasta' || cat === 'Breakfast & Cereal') return 'Store in a cool, dry place.';
 if (cat === 'Spices & Seasonings') return 'Store in a cool, dry place.';
 if (cat === 'Nuts & Snacks') return 'Reseal tightly; keep in a cool, dry place.';

 if (cat === 'Beverages') {
 if (/\bjuice\b|\bmilk\b|\bkefir\b|\bkombucha\b|yogh?urt\s*drink/.test(haystack)) {
 return 'Refrigerate after opening.';
 }
 return null;
 }

 if (cat === 'Winery & Spirits') return 'Store upright in a cool place, away from direct sunlight.';
 if (cat === 'Fruits' || cat === 'Vegetables') return 'Store according to type; most keep best refrigerated.';

 if (cat === 'Household') return 'Store upright in a cool, dry place. Keep out of reach of children.';

 if (cat === 'Personal Care') {
 // Medicinal items get the stronger safety line; cosmetics get a lighter one.
 const n = product.name.toLowerCase();
 const isMedicinal = /lozenge|tablet|capsule|syrup|supplement|vitamin|medicine|remedy|pain relief|antacid|antihistamine|ibuprofen|acetaminophen|aspirin|cough|cold|flu/.test(n);
 return isMedicinal
 ? 'Store in a cool, dry place. Keep out of reach of children.'
 : 'Store in a cool, dry place.';
 }

 return null;
}

// ---- Assembly -----------------------------------------------------------

export function generateNote(product: NoteInput): string {
 // Primary lead: OFF's own description (if it isn't a useless stub).
 // Fallback lead: category-aware guess from the product name.
 const lead = formatLead(product) ?? buildFallbackLead(product);

 const rawTags = [
 ...(product.labels_text || '').split(','),
 ...(product.dietary ?? []),
 ];
 const tags = [...new Set(
 rawTags.map(normalizeTag).filter((t): t is string => t !== null)
 )].slice(0, 4).map(titleCase);

 const nutrition = formatNutritionLine(product);
 const storage = storageHint(product);

 const hasContent =
 !!lead ||
 tags.length > 0 ||
 !!product.allergens?.length ||
 !!product.traces?.length ||
 !!nutrition ||
 !!storage;
 if (!hasContent) return '';

 const sentences: string[] = [];
 if (lead) sentences.push(lead);
 if (tags.length > 0) sentences.push(`${joinWithCommas(tags)}.`);
 if (product.allergens?.length) {
 sentences.push(`Contains: ${product.allergens.map(a => a.toLowerCase()).join(', ')}.`);
 }
 if (product.traces?.length) {
 sentences.push(`May contain: ${product.traces.map(t => t.toLowerCase()).join(', ')}.`);
 }
 if (nutrition) sentences.push(nutrition);
 if (storage) sentences.push(storage);

 return sentences.join(' ');
}
