/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#145CFF',
          dark: '#6EA1FF',
          glow: 'rgba(20,92,255,0.14)',
        },
        secondary: { DEFAULT: '#F0B429', dark: '#FFD15C' },
        accent: { DEFAULT: '#00A991', dark: '#4DDBC7' },
        canvas: { DEFAULT: '#F4F1E8', dark: '#101010' },
        'canvas-raised': { DEFAULT: '#FBF8EF', dark: '#171713' },
        surface: { DEFAULT: '#FFFDF6', dark: '#1E1D19' },
        'surface-muted': { DEFAULT: '#E7E0D1', dark: '#2A2822' },
        'surface-elevated': { DEFAULT: '#FFFFFF', dark: '#26241F' },
        ink: { DEFAULT: '#101010', dark: '#FFFDF6' },
        'ink-soft': { DEFAULT: '#38342D', dark: '#E6DFD0' },
        line: { DEFAULT: '#1B1B1B', dark: '#3B382F' },
        muted: { DEFAULT: '#6D665B', dark: '#B6AC9A' },
        subtle: { DEFAULT: '#8C8375', dark: '#918778' },
        success: '#0E8F58',
        warning: '#D88A00',
        danger: '#E13636',
        info: '#145CFF',
        teal: '#00A991',
        amber: '#F0B429',
      },
      borderRadius: { card: '8px', field: '8px', glass: '8px', bento: '8px' },
      borderWidth: { 3: '3px' },
      fontFamily: {
        sans: ['Outfit_400Regular', 'System'],
        medium: ['Outfit_500Medium', 'System'],
        semibold: ['Outfit_600SemiBold', 'System'],
        bold: ['Outfit_700Bold', 'System'],
        black: ['Outfit_800ExtraBold', 'System'],
        display: ['Fraunces_600SemiBold', 'serif'],
        'display-bold': ['Fraunces_700Bold', 'serif'],
      },
    },
  },
  plugins: [],
};
