/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#FF3366',
          dark: '#FF4D79',
          glow: 'rgba(255,77,121,0.24)',
        },
        secondary: { DEFAULT: '#FFD600', dark: '#FFE033' },
        accent: { DEFAULT: '#00C896', dark: '#1AE0AD' },
        canvas: { DEFAULT: '#F5F4F0', dark: '#0F1410' },
        'canvas-raised': { DEFAULT: '#FBFAF7', dark: '#151C17' },
        surface: { DEFAULT: '#FFFFFF', dark: '#1A221C' },
        'surface-muted': { DEFAULT: '#EFEFE8', dark: '#253028' },
        'surface-elevated': { DEFAULT: '#FFFFFF', dark: '#2A3630' },
        ink: { DEFAULT: '#0A110D', dark: '#F5F4F0' },
        'ink-soft': { DEFAULT: '#3D4742', dark: '#D6DDD8' },
        line: { DEFAULT: '#E2E2D9', dark: '#2C3930' },
        muted: { DEFAULT: '#5C6661', dark: '#A3B3AA' },
        subtle: { DEFAULT: '#6E7871', dark: '#8FA096' },
        success: '#0A9E76',
        warning: '#B78900',
        danger: '#E02D57',
        info: '#0E7490',
        teal: '#00C896',
        amber: '#FFB800',
      },
      borderRadius: { card: '28px', field: '18px', glass: '32px', bento: '32px' },
      borderWidth: { 3: '3px' },
      fontFamily: {
        sans: ['Outfit_400Regular', 'System'],
        medium: ['Outfit_500Medium', 'System'],
        semibold: ['Outfit_600SemiBold', 'System'],
        bold: ['Outfit_700Bold', 'System'],
        black: ['Outfit_800ExtraBold', 'System'],
        display: ['Fraunces_600SemiBold', 'serif'],
        'display-bold': ['Fraunces_700Bold', 'serif'],
      },
    },
  },
  plugins: [],
};
