import { createContext, useContext, ReactNode, useMemo } from 'react';
import { usePantry } from '../hooks/usePantry';
import { useShoppingLists } from '../hooks/useShoppingLists';
import {
  collection,
  doc,
  addDoc,
  deleteDoc,
  serverTimestamp,
  writeBatch,
} from '@react-native-firebase/firestore';
import { db } from '../lib/firebase';
import { useAuth } from './AuthContext';
import { categoryFromName } from '../lib/categories';

type PantryStore = Omit<ReturnType<typeof useShoppingLists>, 'items'> & ReturnType<typeof usePantry>;

const PantryContext = createContext<PantryStore | undefined>(undefined);

export function PantryProvider({ children }: { children: ReactNode }) {
  const { user, householdId } = useAuth();
  const shopping = useShoppingLists();

  const shoppingBridge = useMemo(
    () => ({
      activeListId: shopping.activeListId,
      shoppingList: shopping.shoppingList,
      addAutoItem: async (name: string, unit: string, category: string) => {
        if (!householdId || !shopping.activeListId || !user) return;
        await addDoc(
          collection(db, 'households', householdId, 'shoppingLists', shopping.activeListId, 'items'),
          {
            productName: name,
            quantity: 1,
            unit,
            purchased: false,
            estimatedPrice: 0,
            category: category || categoryFromName(name).id,
            isAutoGenerated: true,
            addedBy: user.uid,
            addedAt: serverTimestamp(),
          },
        );
      },
      removeAutoItems: async (ids: string[]) => {
        if (!householdId || !shopping.activeListId) return;
        const batch = writeBatch(db);
        ids.forEach((id) =>
          batch.delete(doc(db, 'households', householdId, 'shoppingLists', shopping.activeListId!, 'items', id)),
        );
        await batch.commit();
      },
    }),
    [shopping.activeListId, shopping.shoppingList, householdId, user],
  );

  const pantry = usePantry(shoppingBridge);
  const store = { ...shopping, ...pantry };

  return <PantryContext.Provider value={store}>{children}</PantryContext.Provider>;
}

export function usePantryStore() {
  const ctx = useContext(PantryContext);
  if (!ctx) throw new Error('usePantryStore must be used within PantryProvider');
  return ctx;
}
