import React, { ReactNode, useMemo } from 'react';
import { ShoppingProvider, useShopping } from './ShoppingContext';
import { InventoryProvider, useInventory } from './InventoryContext';
import { useAuth } from './AuthContext';
import { useHousehold } from './HouseholdContext';
import { collection, doc, addDoc, serverTimestamp, writeBatch } from '@react-native-firebase/firestore';
import { db } from '../lib/firebase';
import { categoryFromName } from '../lib/categories';

function InventoryProviderBridge({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const { householdId } = useHousehold();
  const shopping = useShopping();

  const shoppingBridge = useMemo(
    () => ({
      activeListId: shopping.activeListId,
      shoppingList: shopping.shoppingList,
      addAutoItem: async (name: string, unit: string, category: string) => {
        if (!householdId || !shopping.activeListId || !user) return;
        await addDoc(
          collection(db, 'households', householdId, 'shoppingLists', shopping.activeListId, 'items'),
          {
            productName: name,
            quantity: 1,
            unit,
            purchased: false,
            estimatedPrice: 0,
            category: category || categoryFromName(name).id,
            isAutoGenerated: true,
            addedBy: user.uid,
            addedAt: serverTimestamp(),
          },
        );
      },
      removeAutoItems: async (ids: string[]) => {
        if (!householdId || !shopping.activeListId) return;
        const batch = writeBatch(db);
        ids.forEach((id) =>
          batch.delete(doc(db, 'households', householdId, 'shoppingLists', shopping.activeListId!, 'items', id)),
        );
        await batch.commit();
      },
    }),
    [shopping.activeListId, shopping.shoppingList, householdId, user],
  );

  return (
    <InventoryProvider shoppingBridge={shoppingBridge}>
      {children}
    </InventoryProvider>
  );
}

export function PantryProvider({ children }: { children: ReactNode }) {
  return (
    <ShoppingProvider>
      <InventoryProviderBridge>
        {children}
      </InventoryProviderBridge>
    </ShoppingProvider>
  );
}

/**
 * Legacy combined hook.
 * @deprecated Use useInventory() or useShopping() directly.
 */
export function usePantryStore() {
  const shopping = useShopping();
  const inventory = useInventory();
  return useMemo(
    () => ({
      ...shopping,
      ...inventory,
      shoppingListItems: shopping.items,
    }),
    [shopping, inventory],
  );
}
